version: '3.2'

services:
  app:
    build: ./
    container_name: 'python3.9-django3.2-base'
    working_dir: /home/user1/app
    command: /usr/local/bin/init.sh
    ports:
      - 8000:8000
      - 2222:2222
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    volumes:
      - ./app:/home/user1/app
